name: Seacoast FLL
highlighter: ""
date: November 22, 2014
broadcasting: false
teams:
  -
    number: 257
    name: Team Teridax
    location: Rochester, NH
    website:
  -
    number: 1487
    name: Robosharks
    location: Strafford, NH
    website:
  -
    number: 4107
    name: Team FUUSEion
    location: Exeter, NH
    website:
  -
    number: 4165
    name: EPICbots
    location: Durham, NH
    website:
  -
    number: 4788
    name: Ferrari Force
    location: Portsmouth, NH
    website:
  -
    number: 4790
    name: The Master Builders
    location: Portsmouth, NH
    website:
  -
    number: 4791
    name: Willy &amp; the TARDISes
    location: Portsmouth, NH
    website:
  -
    number: 4792
    name: Lords of the Brick
    location: Portsmouth, NH
    website:
  -
    number: 4794
    name: The Exeter Cyborgs
    location: Exeter, NH
    website:
  -
    number: 6259
    name: Technic Synergy
    location: Pelham, NH
    website:
  -
    number: 7129
    name: Team Ultrasonic
    location: New Durham, NH
    website:
  -
    number: 7422
    name: The Greenland Determinators
    location: Greenland, NH
    website:
  -
    number: 8557
    name: Dover Brick Miners
    location: Dover, NH
    website:
  -
    number: 8559
    name: Robowave 1
    location: Dover, NH
    website:
  -
    number: 9063
    name: The Hackers
    location: New Durham, NH
    website:
  -
    number: 9068
    name: Paul School Panthers
    location: Wakefield, NH
    website:
  -
    number: 13751
    name: A Bunch of Breakfast
    location: Exeter, NH
    website:
  -
    number: 14880
    name: Oyster River Robo-Cats
    location: Durham, NH
    website:
fll_schedule:
  -
    time: 10:30AM
    description: Pits Open
  -
    time: 11:00AM
    description: Registration Open
  -
    time: 12:00PM
    description: Coaches Meeting
  -
    time: 12:30PM
    description: Opening Ceremony
  -
    time: 1:00PM
    description: Matches and Judging
  -
    time: 2:00PM
    description: Make Your Own Sundae Open
  -
    time: 4:15PM
    description: Finals
  -
    time: 5:15PM
    description: Closing Ceremony
jrfll_schedule:
  -
    time: 1:00PM
    description: Registration Open
  -
    time: 1:20PM
    description: Team Reviewing
  -
    time: 2:00PM
    description: Free Time
  -
    time: 2:30PM
    description: Team Parade (Line Up)
  -
    time: 2:40PM
    description: High Five Ceremony
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      title: Seacoast FLL Qualifier &mdash; November 22, 2014
      description: The Seacoast FIRST Lego League qualifying tournament at University of New Hampshire
      author: Brian Turnbull
